import PDFDocument from 'pdfkit';
import { normalizeDieCutExportData } from './diecutExportUtils.js';

// Vietnamese font paths (Windows system fonts)
const FONT_REGULAR = 'C:\\Windows\\Fonts\\arial.ttf';
const FONT_BOLD = 'C:\\Windows\\Fonts\\arialbd.ttf';

function drawPolygon(doc, polygon) {
  if (!polygon?.length) return;
  doc.moveTo(polygon[0].x, polygon[0].y);
  for (let index = 1; index < polygon.length; index++) {
    doc.lineTo(polygon[index].x, polygon[index].y);
  }
  doc.closePath();
}

function drawGrid(doc, originX, originY, width, height, step) {
  doc.save();
  doc.lineWidth(0.25).strokeColor('#D1D5DB').opacity(0.35);
  for (let x = step; x < width; x += step) {
    doc.moveTo(originX + x, originY).lineTo(originX + x, originY + height).stroke();
  }
  for (let y = step; y < height; y += step) {
    doc.moveTo(originX, originY + y).lineTo(originX + width, originY + y).stroke();
  }
  doc.restore();
}

function drawSheetPage(doc, exportData, sheet, pageIndex) {
  const isPortrait = sheet.sheetHeight >= sheet.sheetWidth;
  doc.addPage({
    size: 'A4',
    layout: isPortrait ? 'portrait' : 'landscape',
    margins: { top: 40, right: 40, bottom: 40, left: 40 }
  });

  const margin = 40;
  const headerHeight = 58;
  const footerHeight = 24;
  const pageWidth = doc.page.width;
  const pageHeight = doc.page.height;
  const drawWidth = pageWidth - margin * 2;
  const drawHeight = pageHeight - margin * 2 - headerHeight - footerHeight;
  const scale = Math.min(drawWidth / sheet.sheetWidth, drawHeight / sheet.sheetHeight);
  const boardWidth = sheet.sheetWidth * scale;
  const boardHeight = sheet.sheetHeight * scale;
  const originX = margin + (drawWidth - boardWidth) / 2;
  const originY = margin + headerHeight + (drawHeight - boardHeight) / 2;

  doc.font(FONT_BOLD).fontSize(16).fillColor('#111827')
    .text(exportData.title, margin, 22, { align: 'center' });

  const infoText = [
    `Sheet ${pageIndex + 1}/${exportData.sheets.length}`,
    `${sheet.sheetWidth} x ${sheet.sheetHeight} mm`,
    `${sheet.placed.length} pieces`,
    sheet.efficiency != null ? `Efficiency ${sheet.efficiency}%` : null,
    exportData.subtitle || null
  ].filter(Boolean).join(' | ');

  doc.font(FONT_REGULAR).fontSize(9).fillColor('#4B5563')
    .text(infoText, margin, 42, { align: 'center' });

  doc.save();
  doc.rect(originX, originY, boardWidth, boardHeight).lineWidth(1.5).strokeColor('#111827').stroke();
  drawGrid(doc, originX, originY, boardWidth, boardHeight, 100 * scale);

  for (const item of sheet.placed) {
    const scaledPolygon = item.polygon.map((point) => ({
      x: originX + point.x * scale,
      y: originY + point.y * scale
    }));

    drawPolygon(doc, scaledPolygon);
    doc.save();
    doc.fillColor(item.color).opacity(0.33).fill();
    doc.restore();

    drawPolygon(doc, scaledPolygon);
    doc.lineWidth(0.85).strokeColor(item.color).stroke();

    if (item.label) {
      const fontSize = Math.max(5, Math.min(9, Math.min(boardWidth, boardHeight) / 75));
      doc.font(FONT_BOLD).fontSize(fontSize).fillColor('#FFFFFF');
      doc.text(
        item.label,
        originX + item.centroid.x * scale - 14,
        originY + item.centroid.y * scale - fontSize * 0.55,
        { width: 28, align: 'center', lineBreak: false }
      );
    }
  }
  doc.restore();

  doc.font(FONT_REGULAR).fontSize(8).fillColor('#6B7280')
    .text('Generated by Die-Cut Nesting', margin, pageHeight - 24, { align: 'center' });
}

export function generateDieCutPdf(payload, stream) {
  const exportData = normalizeDieCutExportData(payload);
  const doc = new PDFDocument({
    autoFirstPage: false,
    compress: true
  });

  doc.pipe(stream);
  exportData.sheets.forEach((sheet, index) => {
    drawSheetPage(doc, exportData, sheet, index);
  });
  doc.end();
}
